sudo: false

language: 
  - android
  - python
jdk:
  - oraclejdk8
python: 3.6
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-28.0.3
    - android-28
install:
  - pip install requests
script: 
  - cd Kuroba
  - chmod +x gradlew
  - ./gradlew build --console plain -x lint
  - python main.py 1234567890 401010 Kuroba\\app\\build\\outputs\\apk\\debug\\Kuroba.apk

notifications:
  email: false