sudo: false
language: android
jdk:
  - oraclejdk8
before_install:
  - cd Kuroba && chmod +x gradlew
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-28.0.3
    - android-28

script: ./gradlew build --console plain -x lint
