sudo: false

language: 
  - android
  - python
jdk:
  - oraclejdk8
python: 3.6
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-28.0.3
    - android-28
install:
  - pip install requests 
script: 
  - cd Kuroba || travis_terminate 1;
  - chmod +x gradlew || travis_terminate 2;
  - ./gradlew build --console plain -x lint || travis_terminate 3;
  - python upload_apk.py 1234567890 401010 http://127.0.0.1:8080 || travis_terminate 4;

notifications:
  email: false