sudo: false

language: 
  - android
  - python
jdk:
  - oraclejdk8
python: "3.6"
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-28.0.3
    - android-28
install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get -y install python3-pip
  - pip3 install requests 
script: 
  - cd Kuroba || travis_terminate 1;
  - chmod +x gradlew || travis_terminate 2;
  - ./gradlew assembleDevDebug --console plain -x lint || travis_terminate 3;
  - python3 upload_apk.py http://94.140.116.243:8080 multi-feature || travis_terminate 4;
env:
  global:
    - secure: "Gi4YgL5P3TgM7uYlpZfw9PVEStCYOPm6R/DaTNBQcvxgVhAp+JS9yAjvSvA1aJQdRKehlIEixBQ820u/9npFO4zQjrhqrLSNMg8nmmXnfF2/SDgVw6CFQfaH4Gf0SvrNLEW+I8KYuVzFhAKIQaPWTbCU6+ychdXytp6CvOX3T7GEHaR7BjdnydJwJW3kr2WV6lQdSrVJlzpvQb3LPG+kHnV7jtKzMAde44jQtqjR/NqkQBnyc8UYvtaqam0JL2L1Fn9AHuqcvHwCDT1DZIVsUP0e9JPCdzqqSMDBGVV+aD/2RbIKdtb/UIyPCiZcuO4TSTQI0ZCmjMsYNU3jHftsyRIehnjE2AM5Q/C2wEEwyq2vWRNBjMfu3QPqwVImGA+Fz1u/I0Q3ZfPfjetxIh1iKKJIqm84N+ykXrKqcjnOAQD/ojqNhxL2wGG1CruXySqLhZdGe3Z44V7bXS3w+bEm0prSMEBI/EIR+cSBNQxQIMpYTC7kRvXah4sVh+PZQoEQ+/EvLUEGayy0O+2I1Bxcpg/WJcVtZnW2Dh5d9MtKp9IAX3Zmbez0wPziQjfmm33IWkojF1p2pj6sNQVNNPC7dtVEnJvcyYC98KB2zk8A2EXuPBBlEhh/Bn7M21N54BSLX7C59SlauPdH/c7G/ilhkAowCZMIX0N5dqLVBRLbe8M="

notifications:
  email: false